# Generated by Django 2.2.4 on 2021-02-28 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favBooksApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='lname',
            new_name='last_name',
        ),
    ]
